// <auto-generated />
namespace OnlineShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_creation_new_fix_bugs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_creation_new_fix_bugs));
        
        string IMigrationMetadata.Id
        {
            get { return "201701222033289_db_creation_new_fix_bugs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
