// <auto-generated />
namespace OnlineShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_new_migration_final : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_new_migration_final));
        
        string IMigrationMetadata.Id
        {
            get { return "201701230745344_db_new_migration_final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
